---
- hosts: localhost
  connection: local
  sudo_user: root
  sudo: False

  tasks:
    - name: Ensure /etc/paths are in the correct order
      sudo: True
      copy: src=files/paths dest=/etc/paths owner=root

    - name: Ensure required repositories are tapped
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask
        - homebrew/dupes
        - homebrew/versions
        - homebrew/php

    - name: Ensure required packages are installed
      homebrew: name={{ item }} state=present
      with_items:
        - ansible
        - automake
        - brew-cask
        - curl
        - elasticsearch
        - git
        - jsonpp
        - nmap
        - node
        - nginx
        - openssl
        - percona-server
        - percona-toolkit
        - redis
        - terminal-notifier
        - youtube-dl
        - wget
        - zsh

    - name: Ensure php is installed
      homebrew: name=php55 install_options=with-fpm

    - name: Ensure php dependencies are installed
      homebrew: name={{ item }} state=present
      with_items:
        - php55-intl
        - php55-mcrypt
        - php55-opcache
        - php55-redis
        - php55-xdebug
        - composer
        - phpunit

    - name: Ensure required applications are installed
      homebrew_cask: name={{ item }} state=present
      with_items:
        - skype
        - bitcasa
        - firefox
        - virtualbox
        - vagrant
        - phpstorm
        - spotify
        - sequel-pro

    - name: Ensure oh-my-zsh is installed
      stat: path=~/.zshrc
      register: omz_file

    - name: Ensure oh-my-zsh is installed
      shell: "curl -L http://install.ohmyz.sh | sh"
      when: omz_file.stat.exists == False

    - name: Ensure rvm is installed
      stat: path=~/.rvm
      register: rvm_folder

    - name: Ensure rvm is installed
      shell: "curl -sSL https://get.rvm.io | bash -s stable --ruby"
      when: rvm_folder.stat.isdir is not defined

    - name: Ensure required npm packages are installed
      npm: name={{ item }} global=yes state=present
      with_items:
        - coffee-script
        - brunch
        - bower

    - name: Ensure required gems are installed
      gem: name={{ item }} state=present user_install=no
      with_items:
        - capifony
        - capistrano_rsync_with_remote_cache
        - sass

    - name: Ensure nginx sites* dirs are present
      file: path=/usr/local/etc/nginx/{{ item }} state=directory
      with_items:
        - 'sites-enabled'

    - name: Ensure nginx configuration file is at the latest version.
      template: src=files/{{ item }} dest=/usr/local/etc/nginx/
      with_items:
        - nginx.conf
        - fastcgi_params

    - name: Ensure nginx vhosts are at the latest version.
      template: src='files/vhost_{{ item }}' dest=/usr/local/etc/nginx/sites-enabled/
      with_items:
        - general
        - sf2

    - name: Ensure php.ini config is in place
      copy: src=files/php.ini dest=/usr/local/etc/php/5.5/

    - name: Ensure that additionals php extensions are in place
      template: src=files/{{ item }} dest=/usr/local/etc/php/5.5/conf.d/
      with_items:
        - xdebug.ini

    - name: Rejoice!
      shell: "terminal-notifier -sound default -group 'terminal-ansible' -title 'Ansible' -subtitle 'Finished' -message 'Mac successfully provisioned!' -activate 'com.apple.Terminal'"

