---
- hosts: localhost
  connection: local

  # vars:
  #   mas_installed_apps:
  #     - { id: 937984704, name: "Amphetamine" }
  #     - { id: 1091189122, name: "Bear" }
  #     - { id: 409183694 , name: "Keynote" }
  #     - { id: 409203825, name: "Numbers" }
  #     - { id: 409201541, name: "Pages" }
  #     - { id: 803453959, name: "Slack" }
  #     - { id: 946399090, name: "Telegram Lite" }

  roles:
    - role: elliotweiser.osx-command-line-tools
    # - role: geerlingguy.mac.mas

  tasks:
    - name: Ensure brew taps are installed
      homebrew_tap:
        name:
          - teamookla/speedtest

    - name: Ensure work related brew taps are installed
      homebrew_tap:
        name:
          - birdayz/kaf
          - common-fate/granted
          - k8sgpt-ai/k8sgpt
          - hashicorp/tap
      when: role == "work"

    - name: Ensure home related brew taps are installed
      homebrew_tap:
        name:
          - siderolabs/tap
      when: role == "home"

    - name: Ensure required packages are installed
      homebrew:
        name:
          - 1password-cli
          - ansible
          - automake
          - awscli
          - cloudflared
          - coreutils # gdate, ...
          - curl
          - diff-pdf
          - dos2unix
          - elixir
          - excel-compare
          - exiftool
          - fdupes
          - ffmpeg
          - fswatch
          - git
          - go
          - gnu-sed
          - iperf3
          - jsonnet
          - jsonpp
          - helm
          - jq
          - k9s
          - krew
          - kubernetes-cli
          - mitmproxy
          - mtr
          - netcat
          - nmap
          - node
          - openssl
          - optipng
          - p7zip
          - pulumi
          - pwgen
          - redis
          - rsync
          - shellcheck
          - speedtest-cli
          - sqlite
          - streamlink
          - teamookla/speedtest/speedtest
          - telnet
          - terminal-notifier
          - tree
          - tor
          - vim
          - yamllint
          - yarn
          - yq
          - yt-dlp
          - watch
          - wget
          - xz
          - zip
        state: present

    - name: Ensure required applications are installed
      homebrew:
        name:
          - k8sgpt-ai/k8sgpt/k8sgpt
          - birdayz/kaf/kaf
          - gitleaks
          - granted
          - mysql
          - steampipe
          - hashicorp/tap/vault
          - hashicorp/tap/terraform
        state: present
      when: role == "work"

    - name: Ensure required applications are installed
      homebrew:
        name:
          - siderolabs/tap/talosctl
        state: present
      when: role == "home"

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - 1password
          - appcleaner
          - discord
          - firefox
          - geekbench
          - google-chrome
          - bruno
          - sublime-text
          - tableplus
          - the-unarchiver
          - visual-studio-code
          - vlc
          - wireshark
          - zoom
        state: present

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - balenaetcher
          - calibre
          - orbstack
          - mediainfo
          - mullvadvpn
          - tor-browser
          - whatsapp
        state: present
      when: role == "home"

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - amazon-chime
          - aws-vault
          - cloudflare-warp
          - grammarly-desktop
          - meetingbar
          - rancher
        state: present
      when: role == "work"

    - name: Proper python setup
      homebrew:
        name:
          - poetry
          - python
        state: present

    - name: Ensure .zshrc file is in place
      copy: src=files/.zshrc_home dest=~/.zshrc
      when: role == "home"

    - name: Ensure .zshrc file is in place
      copy: src=files/.zshrc_work dest=~/.zshrc
      when: role == "work"

    - name: Ensure cleanup script is installed
      copy: src=files/cleanup dest=/usr/local/bin/cleanup mode=0755

    - name: Check if biscuit is installed
      stat: path=/usr/local/bin/biscuit
      register: biscuit_file
      when: role == "work"

    - name: Download biscuit
      get_url:
        url: https://github.com/primait/biscuit/releases/download/v0.1.7/biscuit-darwin_amd64.tgz
        dest: /tmp/biscuit-darwin_amd64.tar.gz
        mode: 0440
      when: role == "work" and biscuit_file.stat.exists == False

    - name: Untar biscuit
      shell: tar xzvf /tmp/biscuit-darwin_amd64.tar.gz && mv biscuit /usr/local/bin/biscuit && chmod 755 /usr/local/bin/biscuit
      when: role == "work" and biscuit_file.stat.exists == False

    - name: Install electro future
      get_url:
        url: https://raw.githubusercontent.com/aleinside/dotfiles/master/future/electro-future.sh
        dest: /usr/local/bin/electro
        mode: 0755
      when: role == "work"

    - name: Rejoice!
      shell: "terminal-notifier -sound default -group 'terminal-ansible' -title 'Ansible' -subtitle 'Finished' -message 'Mac successfully provisioned!' -activate 'com.apple.Terminal'"
