---
- hosts: localhost
  connection: local

  vars:
    mas_email: andreausu@gmail.com
    mas_installed_apps:
      - { id: 1333542190, name: "1Password 7" }
      - { id: 937984704, name: "Amphetamine" }
      - { id: 1091189122, name: "Bear" }
      - { id: 1121192229 , name: "Better" }
      - { id: 409183694 , name: "Keynote" }
      - { id: 409203825, name: "Numbers" }
      - { id: 409201541, name: "Pages" }
      - { id: 803453959, name: "Slack" }
      - { id: 946399090, name: "Telegram Lite" }
      - { id: 1451685025, name: "Wireguard" }

  vars_prompt:
    - name: mas_password
      prompt: "Please insert your Mac App Store password ({{ mas_email }})"

  roles:
    - geerlingguy.mas

  tasks:
    - name: Ensure brew taps are installed
      homebrew_tap:
        name:
          - drone/drone

    - name: Ensure required packages are installed
      homebrew:
        name:
          - ansible
          - automake
          - awscli
          - cmake
          - coreutils # gdate, ...
          - curl
          - diff-pdf
          - dos2unix
          - drone
          - elixir
          - excel-compare
          - exiftool
          - fdupes
          - ffmpeg
          - fswatch
          - git
          - go
          - gnu-sed
          - iperf3
          - jsonnet
          - jsonpp
          - jq
          - kubernetes-cli
          - mitmproxy
          - mkvtoolnix
          - mtr
          - mysql-client
          - netcat
          - nmap
          - node
          - openssl
          - optipng
          - p7zip
          - packer
          - percona-toolkit
          - redis
          - rsync
          # - shellcheck m1 incompatible atm
          - speedtest-cli
          - sqlite
          - streamlink
          - telnet
          - terminal-notifier
          - terraform
          - tree
          - tor
          - vim
          - yamllint
          - yarn
          - youtube-dl
          - watch
          - wget
          - xz
          - zip
        state: present

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - atom
          - docker # docker for mac
          - firefox
          - google-chrome
          - insomnia
          - ngrok
          - sublime-text
          - tableplus
          - the-unarchiver
          - tor-browser
          - tunnelblick
          - visual-studio-code
          - vlc
          - xquartz
          - whatsapp
          - wireshark
        state: present

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - backblaze
          - little-snitch
        state: present
      when: role == "home"

    - name: Ensure required applications are installed
      homebrew_cask:
        name:
          - amazon-chime
          - aws-vault
          - cyberduck
          - discord
          - lastpass
          - microsoft-teams
          - tenable-nessus-agent
          - webex-meetings
          - zoom
        state: present
      when: role == "work"

    - name: Ensure .zshrc file is in place
      copy: src=files/.zshrc dest=~/.zshrc

    - name: Ensure cleanup script is installed
      copy: src=files/cleanup dest=/usr/local/bin/cleanup mode=0755

    - name: Install prima-twig
      gem: name=prima-twig state=present
      when: role == "work"

    - name: Check if biscuit is installed
      stat: path=/usr/local/bin/biscuit
      register: biscuit_file
      when: role == "work"

    - name: Download biscuit
      get_url:
        url: https://github.com/primait/biscuit/releases/download/v0.1.7/biscuit-darwin_amd64.tgz
        dest: /tmp/biscuit-darwin_amd64.tar.gz
        mode: 0440
      when: role == "work" and biscuit_file.stat.exists == False

    - name: Untar biscuit
      shell: tar xzvf /tmp/biscuit-darwin_amd64.tar.gz && mv biscuit /usr/local/bin/biscuit && chmod 755 /usr/local/bin/biscuit
      when: role == "work" and biscuit_file.stat.exists == False

    - name: Install electro future
      get_url:
        url: https://raw.githubusercontent.com/aleinside/dotfiles/master/future/electro-future.sh
        dest: /usr/local/bin/electro
        mode: 0755
      when: role == "work"

    - name: Rejoice!
      shell: "terminal-notifier -sound default -group 'terminal-ansible' -title 'Ansible' -subtitle 'Finished' -message 'Mac successfully provisioned!' -activate 'com.apple.Terminal'"
