---
- hosts: localhost
  connection: local
  sudo_user: root
  sudo: False

  tasks:
    - name: Ensure /etc/paths are in the correct order
      sudo: True
      copy: src=files/paths dest=/etc/paths owner=root

    - name: Ensure required repositories are tapped
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask
        - homebrew/dupes
        - homebrew/versions

    - name: Ensure required packages are installed
      homebrew: name={{ item }} state=present
      with_items:
        - ansible
        - automake
        - awscli
        - brew-cask
        - curl
        - docker
        - docker-compose
        - docker-machine
        - fdupes
        - git
        - jsonpp
        - md5sha1sum
        - netcat
        - nmap
        - openssl
        - optipng
        - qcachegrind
        - redis
        - rsync
        - terminal-notifier
        - youtube-dl
        - wget
        - zsh

    - name: Ensure required applications are installed
      homebrew_cask: name={{ item }} state=present
      with_items:
        - skype
        - firefox
        - virtualbox
        - vagrant
        - phpstorm
        - atom
        - sequel-pro
        - vlc
        - filezilla
        - xquartz
        - wireshark
        - hocus-focus
        - caffeine
        - macclean
        - utorrent
        - calibre
        - gpgtools
        - the-unarchiver
        - tunnelblick
        - dropbox
        - little-snitch

    - name: Ensure oh-my-zsh is installed
      stat: path=~/.zshrc
      register: omz_file

    - name: Ensure oh-my-zsh is installed
      shell: "curl -L http://install.ohmyz.sh | sh"
      when: omz_file.stat.exists == False

    - name: Ensure .zshrc file is in place
      copy: src=files/.zshrc dest=~/.zshrc

    - name: Ensure update_docker_nfs_mounts file is in place
      copy: src=files/update_docker_nfs_mounts.sh dest=/usr/local/bin/update_docker_nfs_mounts mode=0755

    - name: Rejoice!
      shell: "terminal-notifier -sound default -group 'terminal-ansible' -title 'Ansible' -subtitle 'Finished' -message 'Mac successfully provisioned!' -activate 'com.apple.Terminal'"
